Added support for comparing csmith results of jlc and llvm

diff --git a/csmith/Makefile.sub b/csmith/Makefile.sub
--- a/csmith/Makefile.sub
+++ b/csmith/Makefile.sub
@@ -3,14 +3,20 @@ echo ""
 echo "csmith and creduce Make Targets"
 echo "--------------------------------------------------------------------------------"
 echo "csmith-install         Installs csmith"
-echo "csmith-run             Generates c-code until jlc segfaults"
+echo "csmith-run             Generates c-code until jlc aborts"
+echo "csmith-run-abort       Generates c-code until jlc output differs from $(CLANG)"
+echo "csmith-jlc-compile     Compiles the file given by csmith-file= using jlc"
 echo "csmith-clean           Runs make clean and removes generated c-files"
 echo "csmith-purge           Deletes everythin in $(CSMITH_ROOT) except Makefile.sub"
-echo "creduce-run            Runs creduce on the file generated by csmith-run"
+echo "creduce-run            Runs creduce on the C-code generated by csmith-run"
+echo "creduce-run-abort      Runs creduce on generated C-code that cause jlc to abort"
 endef
 .PHONY: csmith-help
 csmith-help:
 	@$(HELP_TEXT_CSMITH)
+
+csmith-file ?= $(CSMITH_ROOT)/test.c
+NCORES ?= 4
 
 ### CSMITH
 
@@ -25,12 +31,30 @@ csmith-install: csmith-purge
 	rmdir /tmp/tmp-csmith
 	cd $(CSMITH_ROOT) && ./configure && make -j 4
 
-.PHONY: csmith-run
-csmith-run: $(CSMITH_ROOT)/src/csmith
+.PHONY: csmith-run-abort
+csmith-run-abort: $(CSMITH_ROOT)/src/csmith
 	set -e;  while [ true ]; do \
 		$(CSMITH_ROOT)/src/csmith > $(CSMITH_ROOT)/test.c; \
 		$(JLM_ROOT)/bin/jlc -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o /dev/null; \
 	done
+
+.PHONY: csmith-run
+csmith-run: $(CSMITH_ROOT)/src/csmith
+	set -e;  while [ true ]; do \
+		$(CSMITH_ROOT)/src/csmith > $(CSMITH_ROOT)/test.c; \
+		$(JLM_ROOT)/bin/jlc -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o $(CSMITH_ROOT)/test.jlc; \
+		$(CLANG) -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o $(CSMITH_ROOT)/test.clang; \
+		$(CSMITH_ROOT)/test.jlc > $(CSMITH_ROOT)/test.jlc-output; \
+		$(CSMITH_ROOT)/test.clang > $(CSMITH_ROOT)/test.clang-output; \
+		diff $(CSMITH_ROOT)/test.jlc-output $(CSMITH_ROOT)/test.clang-output; \
+		if !($$status) then \
+			exit 0; \
+		fi; \
+	done
+
+.PHONY: csmith-jlc-compile
+csmith-jlc-compile:
+		$(JLM_ROOT)/bin/jlc -I${CSMITH_ROOT}/runtime -O $(csmith-file) -o /dev/null;
 
 .PHONY: test.c
 test.c:
@@ -55,14 +79,43 @@ csmith-purge:
 
 ### CREDUCE
 
-$(CSMITH_ROOT)/test-creduce.sh:
+$(CSMITH_ROOT)/test-creduce-abort.sh:
 	@echo "#!/bin/bash" > $@
 	@echo "export PATH=${JLM_ROOT}/bin:$$PATH" >> $@
 	@echo "jlc -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o /dev/null 2> $(CSMITH_ROOT)/test-error" >> $@
 	@echo "grep dumped $(CSMITH_ROOT)/test-error" >> $@
 	@chmod +x $@
 
-.PHONY: $(CSMITH_ROOT)/creduse-run
-creduse-run: $(CSMITH_ROOT)/test-creduce.sh
-	creduce --save-temps $^ $(CSMITH_ROOT)/test.c
+.PHONY: $(CSMITH_ROOT)/test-creduce-compare.sh
+$(CSMITH_ROOT)/test-creduce-compare.sh:
+	@echo "#!/bin/bash" > $@
+	@echo "rm -f $(CSMITH_ROOT)/test.jlc*" >> $@
+	@echo "rm -f $(CSMITH_ROOT)/test.clang*" >> $@
+	@echo "export PATH=${JLM_ROOT}/bin:$$PATH" >> $@
+	@echo "jlc -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o $(CSMITH_ROOT)/test.jlc 2> /dev/null" >> $@
+	@echo 'if [ $$? -eq 1 ]; then' >> $@
+	@echo "	   exit 1;" >> $@
+	@echo "fi;" >> $@
+	@echo "$(CLANG) -I${CSMITH_ROOT}/runtime -O $(CSMITH_ROOT)/test.c -o $(CSMITH_ROOT)/test.clang 2> /dev/null" >> $@
+	@echo 'if [ $$? -eq 1 ]; then' >> $@
+	@echo "	   exit 1;" >> $@
+	@echo "fi;" >> $@
+	@echo "$(CSMITH_ROOT)/test.jlc > $(CSMITH_ROOT)/test.jlc-output" >> $@
+	@echo "$(CSMITH_ROOT)/test.clang > $(CSMITH_ROOT)/test.clang-output" >> $@
+	@echo 'if [ $$? -eq 1 ]; then' >> $@
+	@echo "	   exit 1;" >> $@
+	@echo "fi;" >> $@
+	@echo "diff $(CSMITH_ROOT)/test.jlc-output $(CSMITH_ROOT)/test.clang-output" >> $@
+	@echo 'if [ $$? -eq 1 ]; then' >> $@
+	@echo "	   exit 0;" >> $@
+	@echo "fi;" >> $@
+	@echo "exit 1" >> $@
+	@chmod +x $@
 
+.PHONY: $(CSMITH_ROOT)/creduse-run-abort
+creduse-run-abort: $(CSMITH_ROOT)/test-creduce-abort.sh
+	cd $(CSMITH_ROOT); creduce --n $(NCORES) $^ test.c
+
+.PHONY: $(CSMITH_ROOT)/creduse-run
+creduse-run: $(CSMITH_ROOT)/test-creduce-compare.sh
+	cd $(CSMITH_ROOT); creduce --n $(NCORES) $^ test.c
